// Created with resguy v10 (WIP)
// https://github.com/wootguy/resguy

mistakesplit1.wad
mistakesplit11.wad
mistakesplit12.wad
mistakesplit13.wad
mistakesplit2.wad
mistakesplit3.wad
mistakesplit5.wad
mistakesplit8.wad
mistakesplit9.wad
models/anita1.mdl
models/kisbabu.mdl
models/sence/mistake_coop/anita.mdl
models/sence/mistake_coop/anita1.mdl
models/sence/mistake_coop/anita2.mdl
models/sence/mistake_coop/anita22.mdl
models/sence/mistake_coop/anita3.mdl
models/sence/mistake_coop/Asztal.mdl
models/sence/mistake_coop/Asztal2.mdl
models/sence/mistake_coop/Asztal3.mdl
models/sence/mistake_coop/Asztal4.mdl
models/sence/mistake_coop/badanita.mdl
models/sence/mistake_coop/barney.mdl
models/sence/mistake_coop/barneyt.mdl
models/sence/mistake_coop/beka.mdl
models/sence/mistake_coop/bokor.mdl
models/sence/mistake_coop/bullsquid.mdl
models/sence/mistake_coop/bullsquid01.mdl
models/sence/mistake_coop/bullsquidt.mdl
models/sence/mistake_coop/coat_rack.mdl
models/sence/mistake_coop/crimson.mdl
models/sence/mistake_coop/cso1.mdl
models/sence/mistake_coop/cso2.mdl
models/sence/mistake_coop/cso3.mdl
models/sence/mistake_coop/cso4.mdl
models/sence/mistake_coop/dagadt.mdl
models/sence/mistake_coop/diszperzit.mdl
models/sence/mistake_coop/doc.mdl
models/sence/mistake_coop/doglott.mdl
models/sence/mistake_coop/dokifej.mdl
models/sence/mistake_coop/domb.mdl
models/sence/mistake_coop/drot.mdl
models/sence/mistake_coop/elektromos.mdl
models/sence/mistake_coop/faerg2.mdl
models/sence/mistake_coop/flaska1.mdl
models/sence/mistake_coop/flaska2.mdl
models/sence/mistake_coop/flaska3.mdl
models/sence/mistake_coop/flaska4.mdl
models/sence/mistake_coop/fotel.mdl
models/sence/mistake_coop/fuggony.mdl
models/sence/mistake_coop/gurulo.mdl
models/sence/mistake_coop/guruloasztal.mdl
models/sence/mistake_coop/gyer.mdl
models/sence/mistake_coop/halott.mdl
models/sence/mistake_coop/haz/cipo.mdl
models/sence/mistake_coop/haz/grasoffa.mdl
models/sence/mistake_coop/haz/kaja.mdl
models/sence/mistake_coop/haz/kuka.mdl
models/sence/mistake_coop/haz/nagyszekreny.mdl
models/sence/mistake_coop/haz/noveny.mdl
models/sence/mistake_coop/haz/ora.mdl
models/sence/mistake_coop/haz/p_crowbar.mdl
models/sence/mistake_coop/haz/szekreny1.mdl
models/sence/mistake_coop/haz/szekreny2.mdl
models/sence/mistake_coop/haz/tal.mdl
models/sence/mistake_coop/haz/tanyer.mdl
models/sence/mistake_coop/haz/tanyer2.mdl
models/sence/mistake_coop/haz/telo.mdl
models/sence/mistake_coop/haz/tv.mdl
models/sence/mistake_coop/haz/v_crowbar.mdl
models/sence/mistake_coop/haz/w_crowbar.mdl
models/sence/mistake_coop/haz/w_crowbart.mdl
models/sence/mistake_coop/headcrab.mdl
models/sence/mistake_coop/headcrabt.mdl
models/sence/mistake_coop/hordo.mdl
models/sence/mistake_coop/hordo2.mdl
models/sence/mistake_coop/hulla.mdl
models/sence/mistake_coop/kalapacs.mdl
models/sence/mistake_coop/kez.mdl
models/sence/mistake_coop/kisbabu.mdl
models/sence/mistake_coop/krisa.mdl
models/sence/mistake_coop/kuka.mdl
models/sence/mistake_coop/kulcs1.mdl
models/sence/mistake_coop/kulcs2.mdl
models/sence/mistake_coop/ladersoffa.mdl
models/sence/mistake_coop/lakat.mdl
models/sence/mistake_coop/lampa.mdl
models/sence/mistake_coop/lampa1.mdl
models/sence/mistake_coop/lampa2.mdl
models/sence/mistake_coop/lanc.mdl
models/sence/mistake_coop/mappa.mdl
models/sence/mistake_coop/mask.mdl
models/sence/mistake_coop/mattress.mdl
models/sence/mistake_coop/metalplategibs.mdl
models/sence/mistake_coop/metalplategibs_green.mdl
models/sence/mistake_coop/mgun.mdl
models/sence/mistake_coop/mp5_shell.mdl
models/sence/mistake_coop/mutoasztal.mdl
models/sence/mistake_coop/naplo.mdl
models/sence/mistake_coop/noveny.mdl
models/sence/mistake_coop/null.mdl
models/sence/mistake_coop/orvos.mdl
models/sence/mistake_coop/p_aps.mdl
models/sence/mistake_coop/p_spas12.mdl
models/sence/mistake_coop/papir1.mdl
models/sence/mistake_coop/papir2.mdl
models/sence/mistake_coop/papir3.mdl
models/sence/mistake_coop/papirok.mdl
models/sence/mistake_coop/retyo.mdl
models/sence/mistake_coop/rpgrocket.mdl
models/sence/mistake_coop/rpk_shell.mdl
models/sence/mistake_coop/shell.mdl
models/sence/mistake_coop/spas12_shell.mdl
models/sence/mistake_coop/szek.mdl
models/sence/mistake_coop/szek1.mdl
models/sence/mistake_coop/szek2.mdl
models/sence/mistake_coop/szek3.mdl
models/sence/mistake_coop/szek4.mdl
models/sence/mistake_coop/szekreny.mdl
models/sence/mistake_coop/szekreny2.mdl
models/sence/mistake_coop/szekreny3.mdl
models/sence/mistake_coop/szobor1.mdl
models/sence/mistake_coop/szobor2.mdl
models/sence/mistake_coop/szobor3.mdl
models/sence/mistake_coop/ulesek.mdl
models/sence/mistake_coop/v_aps.mdl
models/sence/mistake_coop/v_spas12.mdl
models/sence/mistake_coop/val_shell.mdl
models/sence/mistake_coop/vas.mdl
models/sence/mistake_coop/virag.mdl
models/sence/mistake_coop/w_aps.mdl
models/sence/mistake_coop/w_spas12.mdl
models/sence/mistake_coop/w_spas12_ammo.mdl
models/sence/mistake_coop/w_spas12t.mdl
models/sence/mistake_coop/w_suit.mdl
models/sence/mistake_coop/w_suitt.mdl
models/sence/mistake_coop/zar.mdl
models/sence/mistake_coop/zombie_eyes.mdl
models/sence/mistake_coop/zombie_slow.mdl
models/sence/mistake_coop/ZombieBaba.mdl
models/sence/mistake_coop/zombika.mdl
models/sence/mistake_coop/zsak.mdl
sound/player/pl_wood_scr1.wav
sound/player/pl_wood_scr2.wav
sound/player/pl_wood_scr3.wav
sound/player/pl_wood_scr4.wav
sound/sence/mistake_coop/bullchicken/bc_acid1.wav
sound/sence/mistake_coop/bullchicken/bc_acid2.wav
sound/sence/mistake_coop/bullchicken/bc_attack1.wav
sound/sence/mistake_coop/bullchicken/bc_attack2.wav
sound/sence/mistake_coop/bullchicken/bc_attack3.wav
sound/sence/mistake_coop/bullchicken/bc_attackgrowl.wav
sound/sence/mistake_coop/bullchicken/bc_attackgrowl2.wav
sound/sence/mistake_coop/bullchicken/bc_attackgrowl3.wav
sound/sence/mistake_coop/bullchicken/bc_bite1.wav
sound/sence/mistake_coop/bullchicken/bc_bite2.wav
sound/sence/mistake_coop/bullchicken/bc_bite3.wav
sound/sence/mistake_coop/bullchicken/bc_die1.wav
sound/sence/mistake_coop/bullchicken/bc_die2.wav
sound/sence/mistake_coop/bullchicken/bc_die3.wav
sound/sence/mistake_coop/bullchicken/bc_idle1.wav
sound/sence/mistake_coop/bullchicken/bc_idle2.wav
sound/sence/mistake_coop/bullchicken/bc_idle3.wav
sound/sence/mistake_coop/bullchicken/bc_idle4.wav
sound/sence/mistake_coop/bullchicken/bc_idle5.wav
sound/sence/mistake_coop/bullchicken/bc_pain1.wav
sound/sence/mistake_coop/bullchicken/bc_pain2.wav
sound/sence/mistake_coop/bullchicken/bc_pain3.wav
sound/sence/mistake_coop/bullchicken/bc_pain4.wav
sound/sence/mistake_coop/bullchicken/bc_spithit1.wav
sound/sence/mistake_coop/bullchicken/bc_spithit2.wav
sound/sence/mistake_coop/bullchicken/bc_spithit3.wav
sound/sence/mistake_coop/buttons/button10.wav
sound/sence/mistake_coop/buttons/button8.wav
sound/sence/mistake_coop/buttons/latchlocked1.wav
sound/sence/mistake_coop/buttons/latchlocked2.wav
sound/sence/mistake_coop/buttons/latchunlocked1.wav
sound/sence/mistake_coop/buttons/latchunlocked2.wav
sound/sence/mistake_coop/common/bodydrop1.wav
sound/sence/mistake_coop/common/bodydrop2.wav
sound/sence/mistake_coop/common/bodydrop3.wav
sound/sence/mistake_coop/common/bodydrop4.wav
sound/sence/mistake_coop/common/bodysplat.wav
sound/sence/mistake_coop/common/npc_step1.wav
sound/sence/mistake_coop/common/npc_step2.wav
sound/sence/mistake_coop/common/npc_step3.wav
sound/sence/mistake_coop/common/npc_step4.wav
sound/sence/mistake_coop/common/wpn_denyselect.wav
sound/sence/mistake_coop/common/wpn_hudoff.wav
sound/sence/mistake_coop/common/wpn_hudon.wav
sound/sence/mistake_coop/common/wpn_moveselect.wav
sound/sence/mistake_coop/common/wpn_select.wav
sound/sence/mistake_coop/debris/bustglass1.wav
sound/sence/mistake_coop/debris/bustglass2.wav
sound/sence/mistake_coop/debris/bustglass3.wav
sound/sence/mistake_coop/debris/bustmetal1.wav
sound/sence/mistake_coop/debris/bustmetal2.wav
sound/sence/mistake_coop/debris/metal1.wav
sound/sence/mistake_coop/debris/metal2.wav
sound/sence/mistake_coop/debris/metal3.wav
sound/sence/mistake_coop/debris/metal4.wav
sound/sence/mistake_coop/doors/doormove10.wav
sound/sence/mistake_coop/doors/doormove4.wav
sound/sence/mistake_coop/doors/doormove6.wav
sound/sence/mistake_coop/doors/doormove7.wav
sound/sence/mistake_coop/doors/doormove8.wav
sound/sence/mistake_coop/doors/doormove9.wav
sound/sence/mistake_coop/doors/doorstop1.wav
sound/sence/mistake_coop/doors/doorstop3.wav
sound/sence/mistake_coop/doors/doorstop4.wav
sound/sence/mistake_coop/doors/doorstop6.wav
sound/sence/mistake_coop/headcrab/hc_alert1.wav
sound/sence/mistake_coop/headcrab/hc_alert2.wav
sound/sence/mistake_coop/headcrab/hc_attack1.wav
sound/sence/mistake_coop/headcrab/hc_attack2.wav
sound/sence/mistake_coop/headcrab/hc_attack3.wav
sound/sence/mistake_coop/headcrab/hc_die1.wav
sound/sence/mistake_coop/headcrab/hc_die2.wav
sound/sence/mistake_coop/headcrab/hc_headbite.wav
sound/sence/mistake_coop/headcrab/hc_idle1.wav
sound/sence/mistake_coop/headcrab/hc_idle2.wav
sound/sence/mistake_coop/headcrab/hc_idle3.wav
sound/sence/mistake_coop/headcrab/hc_idle4.wav
sound/sence/mistake_coop/headcrab/hc_idle5.wav
sound/sence/mistake_coop/headcrab/hc_pain1.wav
sound/sence/mistake_coop/headcrab/hc_pain2.wav
sound/sence/mistake_coop/headcrab/hc_pain3.wav
sound/sence/mistake_coop/interf.wav
sound/sence/mistake_coop/items/9mmclip1.wav
sound/sence/mistake_coop/items/9mmclip2.wav
sound/sence/mistake_coop/items/ammopickup1.wav
sound/sence/mistake_coop/items/ammopickup2.wav
sound/sence/mistake_coop/items/flashlight11.wav
sound/sence/mistake_coop/items/gunpickup1.wav
sound/sence/mistake_coop/items/gunpickup2.wav
sound/sence/mistake_coop/items/gunpickup3.wav
sound/sence/mistake_coop/items/gunpickup4.wav
sound/sence/mistake_coop/items/smallmedkit1.wav
sound/sence/mistake_coop/items/smallmedkit2.wav
sound/sence/mistake_coop/items/weapondrop.wav
sound/sence/mistake_coop/music/music8.mp3
sound/sence/mistake_coop/player/pl_asf1.wav
sound/sence/mistake_coop/player/pl_asf2.wav
sound/sence/mistake_coop/player/pl_asf3.wav
sound/sence/mistake_coop/player/pl_asf4.wav
sound/sence/mistake_coop/player/pl_beton1.wav
sound/sence/mistake_coop/player/pl_beton2.wav
sound/sence/mistake_coop/player/pl_beton3.wav
sound/sence/mistake_coop/player/pl_beton4.wav
sound/sence/mistake_coop/player/pl_dirt1.wav
sound/sence/mistake_coop/player/pl_dirt2.wav
sound/sence/mistake_coop/player/pl_dirt3.wav
sound/sence/mistake_coop/player/pl_dirt4.wav
sound/sence/mistake_coop/player/pl_duct1.wav
sound/sence/mistake_coop/player/pl_duct2.wav
sound/sence/mistake_coop/player/pl_duct3.wav
sound/sence/mistake_coop/player/pl_duct4.wav
sound/sence/mistake_coop/player/pl_fallpain1.wav
sound/sence/mistake_coop/player/pl_fallpain2.wav
sound/sence/mistake_coop/player/pl_fallpain3.wav
sound/sence/mistake_coop/player/pl_grass1.wav
sound/sence/mistake_coop/player/pl_grass2.wav
sound/sence/mistake_coop/player/pl_grass3.wav
sound/sence/mistake_coop/player/pl_grass4.wav
sound/sence/mistake_coop/player/pl_jump1.wav
sound/sence/mistake_coop/player/pl_jump2.wav
sound/sence/mistake_coop/player/pl_jumpland2.wav
sound/sence/mistake_coop/player/pl_ladder1.wav
sound/sence/mistake_coop/player/pl_ladder2.wav
sound/sence/mistake_coop/player/pl_ladder3.wav
sound/sence/mistake_coop/player/pl_ladder4.wav
sound/sence/mistake_coop/player/pl_metal1.wav
sound/sence/mistake_coop/player/pl_metal2.wav
sound/sence/mistake_coop/player/pl_metal3.wav
sound/sence/mistake_coop/player/pl_metal4.wav
sound/sence/mistake_coop/player/pl_pain2.wav
sound/sence/mistake_coop/player/pl_pain4.wav
sound/sence/mistake_coop/player/pl_pain5.wav
sound/sence/mistake_coop/player/pl_pain6.wav
sound/sence/mistake_coop/player/pl_pain7.wav
sound/sence/mistake_coop/player/pl_shell1.wav
sound/sence/mistake_coop/player/pl_shell2.wav
sound/sence/mistake_coop/player/pl_shell3.wav
sound/sence/mistake_coop/player/pl_slosh1.wav
sound/sence/mistake_coop/player/pl_slosh2.wav
sound/sence/mistake_coop/player/pl_slosh3.wav
sound/sence/mistake_coop/player/pl_slosh4.wav
sound/sence/mistake_coop/player/pl_step1.wav
sound/sence/mistake_coop/player/pl_step2.wav
sound/sence/mistake_coop/player/pl_step3.wav
sound/sence/mistake_coop/player/pl_step4.wav
sound/sence/mistake_coop/player/pl_wood1.wav
sound/sence/mistake_coop/player/pl_wood2.wav
sound/sence/mistake_coop/player/pl_wood3.wav
sound/sence/mistake_coop/player/pl_wood4.wav
sound/sence/mistake_coop/roach/rch_die.wav
sound/sence/mistake_coop/roach/rch_smash.wav
sound/sence/mistake_coop/roach/rch_walk.wav
sound/sence/mistake_coop/weapons/cbar_hit1.wav
sound/sence/mistake_coop/weapons/cbar_hit2.wav
sound/sence/mistake_coop/weapons/cbar_hitbod1.wav
sound/sence/mistake_coop/weapons/cbar_hitbod2.wav
sound/sence/mistake_coop/weapons/cbar_hitbod3.wav
sound/sence/mistake_coop/weapons/cbar_miss1.wav
sound/sence/mistake_coop/weapons/glock_fire.wav
sound/sence/mistake_coop/weapons/ric1.wav
sound/sence/mistake_coop/weapons/ric2.wav
sound/sence/mistake_coop/weapons/ric3.wav
sound/sence/mistake_coop/weapons/ric4.wav
sound/sence/mistake_coop/weapons/ric5.wav
sound/sence/mistake_coop/weapons/spas12-1.wav
sound/sence/mistake_coop/weapons/spas12-2.wav
sound/sence/mistake_coop/weapons/spas12_insertshell.wav
sound/sence/mistake_coop/weapons/spas12_pump.wav
sound/sence/mistake_coop/weapons/sshell1.wav
sound/sence/mistake_coop/weapons/sshell2.wav
sound/sence/mistake_coop/weapons/sshell3.wav
sound/sence/mistake_coop/zombie/claw_miss1.wav
sound/sence/mistake_coop/zombie/claw_miss2.wav
sound/sence/mistake_coop/zombie/claw_strike1.wav
sound/sence/mistake_coop/zombie/claw_strike2.wav
sound/sence/mistake_coop/zombie/claw_strike3.wav
sound/sence/mistake_coop/zombie/zo_alert10.wav
sound/sence/mistake_coop/zombie/zo_alert20.wav
sound/sence/mistake_coop/zombie/zo_alert30.wav
sound/sence/mistake_coop/zombie/zo_attack1.wav
sound/sence/mistake_coop/zombie/zo_attack2.wav
sound/sence/mistake_coop/zombie/zo_idle1.wav
sound/sence/mistake_coop/zombie/zo_idle2.wav
sound/sence/mistake_coop/zombie/zo_idle3.wav
sound/sence/mistake_coop/zombie/zo_idle4.wav
sound/sence/mistake_coop/zombie/zo_pain1.wav
sound/sence/mistake_coop/zombie/zo_pain2.wav
sound/weapons/rpk_fire1.wav
sprites/buzz/sence/mistake_coop/buzz_kust0.spr
sprites/buzz/sence/mistake_coop/buzz_zasvet.spr
sprites/sence/mistake_coop/ablaktukor.spr
sprites/sence/mistake_coop/buzz/buzzer_derevo1.spr
sprites/sence/mistake_coop/buzz/buzzer_derevo2.spr
sprites/sence/mistake_coop/buzz/buzzer_myxu.spr
sprites/sence/mistake_coop/buzz/buzzer_stvol_dereva2.spr
sprites/sence/mistake_coop/buzz/buzzer_travka1.spr
sprites/sence/mistake_coop/buzz/buzzer_travka2.spr
sprites/sence/mistake_coop/buzz/buzzer_travka3.spr
sprites/sence/mistake_coop/buzzer_der1_test.spr
sprites/sence/mistake_coop/forgive.spr
sprites/sence/mistake_coop/hi_rain.spr
sprites/sence/mistake_coop/highlight.spr
sprites/sence/mistake_coop/machinegun.spr
sprites/sence/mistake_coop/muzzleflash1.spr
sprites/sence/mistake_coop/null.spr
sprites/sence/mistake_coop/richo1.spr
sprites/sence/mistake_coop/snowflake.spr
sprites/sence/mistake_coop/stmbal1.spr
sprites/sence/mistake_coop/tukorkep.spr
sprites/sence/mistake_coop/wsplash_x.spr
