// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

halflife.wad
lcd_display.wad
liquids.wad
models/bleachbones.mdl
models/bridge/vollight3.mdl
models/cretegibs.mdl
models/holo.mdl
models/hunger/vegitation/tree1.mdl
models/hunger/vegitation/tree2.mdl
models/mortarshell.mdl
models/ragemap2021/crystal.mdl
models/ragemap2021/hat.mdl
models/ragemap2021/nuke_case.mdl
models/wheelchair_sci.mdl
models/wheelchair_sci01.mdl
models/wheelchair_sci02.mdl
models/woodgibs.mdl
nw.wad
ragemap2021.wad
sound/ambience/bigwarning.wav
sound/ambience/burning1.wav
sound/ambience/flameburst1.wav
sound/ambience/goal_1.wav
sound/ambience/particle_suck2.wav
sound/ambience/pulsemachine.wav
sound/ambience/siren.wav
sound/ambience/techamb1.wav
sound/buttons/bell1.wav
sound/buttons/blip1.wav
sound/buttons/button11.wav
sound/buttons/lightswitch2.wav
sound/common/nuke_explode.wav
sound/debris/alien_teleport.wav
sound/debris/beamstart5.wav
sound/debris/beamstart6.wav
sound/doors/doormove1.wav
sound/doors/doorstop6.wav
sound/doors/doorstop8.wav
sound/holo/holointro.wav
sound/holo/holostn1.wav
sound/holo/holostn10.wav
sound/holo/holostn10a.wav
sound/holo/holostn11.wav
sound/holo/holostn13.wav
sound/holo/holostn15.wav
sound/holo/holostn16.wav
sound/holo/holostn2.wav
sound/holo/holostn3.wav
sound/holo/holostn4.wav
sound/holo/holostn5.wav
sound/holo/holostn6.wav
sound/holo/holostn7.wav
sound/holo/holostn8.wav
sound/holo/holostn9.wav
sound/misc/r_tele3.wav
sound/misc/tuner_blip1.wav
sound/plats/elevbell1.wav
sound/plats/elevmove2.wav
sound/plats/talkstop1.wav
sound/plats/ttrain1.wav
sound/ragemap2021/AlexC/Dubmood_-_Afterburner.xm
sound/ragemap2021/AlexC/Mr_Death_-_12th_moon_rising.xm
sound/ragemap2021/AlexC/Rez_-_R0t0f3ul.mod
sound/ragemap2021/AlexC/WONDERBOY_-_My_south_west.xm
sound/ragemap2021/demolite/awsad.mp3
sound/ragemap2021/demolite/cheering.mp3
sound/ragemap2021/demolite/demo_quiz.mp3
sound/ragemap2021/demolite/show_intro.mp3
sound/ragemap2021/demolite/show_outro.mp3
sound/ragemap2021/hezus/alarm.mp3
sound/ragemap2021/hezus/beep.wav
sound/ragemap2021/hezus/boo.mp3
sound/ragemap2021/hezus/cheer.mp3
sound/ragemap2021/hezus/emergency.wav
sound/ragemap2021/hezus/flush.wav
sound/ragemap2021/hezus/hez_show.mp3
sound/ragemap2021/hezus/hez_show2.mp3
sound/ragemap2021/hezus/static.wav
sound/ragemap2021/outro.mp3
sound/ragemap2021/rc/gman_brains.wav
sound/ragemap2021/rc/gman_candidates.wav
sound/ragemap2021/rc/gman_explain.wav
sound/ragemap2021/rc/gman_explain2.wav
sound/ragemap2021/rc/gman_first_question.wav
sound/ragemap2021/rc/gman_fun.wav
sound/ragemap2021/rc/gman_hm.wav
sound/ragemap2021/rc/gman_no1.wav
sound/ragemap2021/rc/gman_no2.wav
sound/ragemap2021/rc/gman_no3.wav
sound/ragemap2021/rc/gman_toilet.wav
sound/ragemap2021/rc/gman_welcome.wav
sound/ragemap2021/rc/gman_yes1.wav
sound/ragemap2021/rc/gman_yes2.wav
sound/ragemap2021/rc/gman_yes3.wav
sound/ragemap2021/rc/live.wav
sound/ragemap2021/rc/rc_rage21.ogg
sound/ragemap2021/rc/rc_rage21_long.ogg
sound/ragemap2021/rc/rc_theme.ogg
sound/ragemap2021/zurdo/builder.mp3
sound/scientist/sneeze.wav
sound/scientist/sniffle.wav
sound/scientist/tram.wav
sound/vox/biohazard.wav
sound/vox/detected.wav
sound/vox/warning.wav
sprites/animglow01.spr
sprites/blueflare2.spr
sprites/boss_glow.spr
sprites/e-tele1.spr
sprites/enter1.spr
sprites/flame2.spr
sprites/flare1.spr
sprites/flare3.spr
sprites/glow01.spr
sprites/glow03.spr
sprites/laserbeam.spr
sprites/lighting/glow.spr
sprites/mushroom.spr
sprites/ragemap2021/rc/ball.spr
sprites/ragemap2021/rc/hud_0.spr
sprites/ragemap2021/rc/hud_1.spr
sprites/ragemap2021/rc/hud_2.spr
sprites/ragemap2021/rc/hud_3.spr
sprites/ragemap2021/rc/hud_4.spr
sprites/ragemap2021/rc/hud_5.spr
sprites/ragemap2021/rc/hud_6.spr
sprites/ragemap2021/rc/hud_7.spr
sprites/ragemap2021/rc/hud_8.spr
sprites/ragemap2021/rc/hud_9.spr
sprites/ragemap2021/rc/hud_balls.spr
sprites/ragemap2021/rc/hud_stars.spr
sprites/ragemap2021/sign_alexc.spr
sprites/ragemap2021/sign_bonk.spr
sprites/ragemap2021/sign_demolite.spr
sprites/ragemap2021/sign_erty.spr
sprites/ragemap2021/sign_hezus.spr
sprites/ragemap2021/sign_rage.spr
sprites/ragemap2021/sign_rc.spr
sprites/ragemap2021/sign_svboy.spr
sprites/ragemap2021/sign_zurdo.spr
sprites/xsmoke3.spr
sprites/xsmoke4.spr
sprites/yelflare1.spr
sprites/zerogxplode.spr
xeno.wad
