array <array<string>> capitols = {
	{ "Sukhumi",					"Abkhazia" },
	{ "Kabul",						"Afghanistan" },
	{ "Mariehamn",					"Åland Islands" },
	{ "Tirana",						"Albania"	 },
	{ "Algiers",					"Algeria" },
	{ "Pago Pago",					"American Samoa" },
	{ "Andorra la Vella",	 		"Andorra" },
	{ "Luanda",						"Angola" },
	{ "The Valley",					"Anguilla" },
	{ "St. John's",					"Antigua and Barbuda" },
	{ "Buenos Aires",	 			"Argentina" },
	{ "Yerevan",					"Armenia" },
	{ "Stepanakert", 	 			"Artsakh" },
	{ "Oranjestad",					"Aruba" },
	{ "Georgetown",					"Ascension Island" },
	{ "Canberra",					"Australia" },
	{ "Vienna",						"Austria" },
	{ "Baku",						"Azerbaijan" },
	{ "Nassau",						"Bahamas" },
	{ "Manama",						"Bahrain" },
	{ "Dhaka",						"Bangladesh" },
	{ "Bridgetown",					"Barbados" },
	{ "Minsk",						"Belarus" },
	{ "Brussels",					"Belgium" },
	{ "Belmopan",					"Belize" },
	{ "Porto-Novo",					"Benin" },
	{ "Hamilton",					"Bermuda" },
	{ "Thimphu",					"Bhutan" },
	{ "Sucre",						"Bolivia" },
	{ "Sarajevo",					"Bosnia and Herzegovina" },
	{ "Gaborone",					"Botswana" },
	{ "Brasília",					"Brazil" },
	{ "Road Town",					"British Virgin Islands" },
	{ "Bandar Seri Begawan",		"Brunei" },
	{ "Sofia",						"Bulgaria" },
	{ "Ouagadougou", 	 			"Burkina Faso" },
	{ "Gitega",				 		"Burundi" },
	{ "Phnom Penh",					"Cambodia" },
	{ "Yaoundé",					"Cameroon" },
	{ "Ottawa",						"Canada" },
	{ "Praia",						"Cape Verde" },
	{ "George Town", 	 			"Cayman Islands" },
	{ "Bangui",						"Central African Republic" },
	{ "N'Djamena",					"Chad" },
	{ "Santiago",					"Chile" },
	{ "Beijing",					"China" },
	{ "Flying Fish Cove",	 		"Christmas Island" },
	{ "West Island", 	 			"Cocos (Keeling) Islands" },
	{ "Bogotá",						"Colombia" },
	{ "Moroni",						"Comoros" },
	{ "Brazzaville", 	 			"Congo" },
	{ "Avarua",						"Cook Islands" },
	{ "San José",					"Costa Rica" },
	{ "Zagreb",						"Croatia" },
	{ "Havana",						"Cuba" },
	{ "Willemstad",					"Curaçao" },
	{ "Nicosia",					"Cyprus" },
	{ "Prague",						"Czech Republic" },
	{ "Kinshasa",					"Democratic Republic of the Congo" },
	{ "Copenhagen",					"Denmark" },
	{ "Djibouti",					"Djibouti" },
	{ "Roseau",						"Dominica" },
	{ "Santo Domingo",	 			"Dominican Republic" },
	{ "Dili",						"East Timor" },
	{ "Quito",						"Ecuador" },
	{ "Cairo",						"Egypt" },
	{ "San Salvador",	 			"El Salvador" },
	{ "Malabo",						"Equatorial Guinea" },
	{ "Asmara",						"Eritrea" },
	{ "Tallinn",					"Estonia" },
	{ "Lobamba",					"Eswatini" },
	{ "Addis Ababa", 	 			"Ethiopia" },
	{ "Stanley",					"Falkland Islands" },
	{ "Tórshavn",					"Faroe Islands" },
	{ "Suva",						"Fiji" },
	{ "Helsinki",					"Finland" },
	{ "Paris",						"France" },
	{ "Papeete",					"French Polynesia" },
	{ "Libreville",					"Gabon" },
	{ "Tbilisi",					"Georgia" },
	{ "Berlin",						"Germany" },
	{ "Accra",						"Ghana" },
	{ "Gibraltar",					"Gibraltar" },
	{ "Athens",						"Greece" },
	{ "Nuuk",						"Greenland" },
	{ "St. George's",	 			"Grenada" },
	{ "Hagåtña",					"Guam" },
	{ "Guatemala City",	 			"Guatemala" },
	{ "St. Peter Port", 	 		"Guernsey" },
	{ "Conakry",					"Guinea" },
	{ "Bissau",						"Guinea-Bissau" },
	{ "Georgetown",					"Guyana" },
	{ "Port-au-Prince",				"Haiti" },
	{ "Tegucigalpa", 	 			"Honduras" },
	{ "Budapest",					"Hungary" },
	{ "Reykjavík",					"Iceland" },
	{ "New Delhi",					"India" },
	{ "Jakarta",					"Indonesia" },
	{ "Tehran",						"Iran" },
	{ "Baghdad",					"Iraq" },
	{ "Dublin",						"Ireland" },
	{ "Douglas",					"Isle of Man" },
	{ "Tel Aviv",					"Israel" },
	{ "Rome",						"Italy" },
	{ "Yamoussoukro",				"Ivory Coast" },
	{ "Kingston",					"Jamaica" },
	{ "Tokyo",						"Japan" },
	{ "St. Helier",					"Jersey" },
	{ "Amman",						"Jordan" },
	{ "Nur-Sultan",					"Kazakhstan" },
	{ "Nairobi",					"Kenya" },
	{ "South Tarawa",	 			"Kiribati" },
	{ "Pristina",					"Kosovo" },
	{ "Kuwait City",	 			"Kuwait" },
	{ "Bishkek",					"Kyrgyzstan" },
	{ "Vientiane",					"Laos" },
	{ "Riga",						"Latvia" },
	{ "Beirut",						"Lebanon" },
	{ "Maseru",						"Lesotho" },
	{ "Monrovia",					"Liberia" },
	{ "Tripoli",					"Libya" },
	{ "Vaduz",						"Liechtenstein" },
	{ "Vilnius",					"Lithuania" },
	{ "Luxembourg",					"Luxembourg" },
	{ "Antananarivo",	 			"Madagascar" },
	{ "Lilongwe",					"Malawi" },
	{ "Kuala Lumpur",	 			"Malaysia" },
	{ "Malé",						"Maldives" },
	{ "Bamako",						"Mali" },
	{ "Valletta",					"Malta" },
	{ "Majuro",						"Marshall Islands" },
	{ "Nouakchott",					"Mauritania" },
	{ "Port Louis",					"Mauritius" },
	{ "Mexico City",	 			"Mexico" },
	{ "Palikir",					"Micronesia" },
	{ "Chișinău",					"Moldova" },
	{ "Monaco",						"Monaco" },
	{ "Ulaanbaatar",	 			"Mongolia" },
	{ "Podgorica",					"Montenegro" },
	{ "Plymouth",					"Montserrat" },
	{ "Rabat",						"Morocco" },
	{ "Maputo",						"Mozambique" },
	{ "Naypyidaw",					"Myanmar" },
	{ "Windhoek",					"Namibia" },
	{ "Yaren",						"Nauru" },
	{ "Kathmandu",					"Nepal" },
	{ "Amsterdam",					"Netherlands" },
	{ "Nouméa",						"New Caledonia" },
	{ "Wellington",					"New Zealand" },
	{ "Managua",					"Nicaragua" },
	{ "Niamey",						"Niger" },
	{ "Abuja",						"Nigeria" },
	{ "Alofi",						"Niue" },
	{ "Kingston",					"Norfolk Island" },
	{ "Pyongyang",					"North Korea" },
	{ "Skopje",						"North Macedonia" },
	{ "Saipan",						"Northern Mariana Islands" },
	{ "Oslo",						"Norway" },
	{ "Muscat",						"Oman" },
	{ "Islamabad",					"Pakistan" },
	{ "Ngerulmud",					"Palau" },
	{ "Jerusalem",					"Palestine" },
	{ "Panama City",	 			"Panama" },
	{ "Port Moresby",	 			"Papua New Guinea" },
	{ "Asunción",					"Paraguay" },
	{ "Lima",						"Peru" },
	{ "Manila",						"Philippines" },
	{ "Adamstown",					"Pitcairn Islands" },
	{ "Warsaw",						"Poland" },
	{ "Lisbon",						"Portugal" },
	{ "San Juan",					"Puerto Rico" },
	{ "Doha",						"Qatar" },
	{ "Bucharest",					"Romania" },
	{ "Moscow",						"Russia" },
	{ "Kigali",						"Rwanda" },
	{ "Gustavia",					"Saint Barthélemy" },
	{ "Jamestown",					"Saint Helena" },
	{ "Basseterre",					"Saint Kitts and Nevis" },
	{ "Castries",					"Saint Lucia" },
	{ "Marigot",					"Saint Martin" },
	{ "St. Pierre",					"Saint Pierre and Miquelon" },
	{ "Kingstown",					"Saint Vincent and the Grenadines" },
	{ "Apia",						"Samoa" },
	{ "San Marino",					"San Marino" },
	{ "São Tomé",					"São Tomé and Príncipe" },
	{ "Riyadh",						"Saudi Arabia" },
	{ "Dakar",						"Senegal" },
	{ "Belgrade",					"Serbia" },
	{ "Victoria",					"Seychelles" },
	{ "Freetown",					"Sierra Leone" },
	{ "Singapore",					"Singapore" },
	{ "Philipsburg",	 			"Sint Maarten" },
	{ "Bratislava",					"Slovakia" },
	{ "Ljubljana",					"Slovenia" },
	{ "Honiara",					"Solomon Islands" },
	{ "Mogadishu",					"Somalia" },
	{ "Hargeisa",					"Somaliland" },
	{ "Bloemfontein",				"South Africa" },
	{ "Cape Town",					"South Africa" },
	{ "Pretoria",					"South Africa" },
	{ "King Edward Point", 			"South Georgia and the South Sandwich Islands" },
	{ "Seoul",						"South Korea" },
	{ "Tskhinvali",					"South Ossetia" },
	{ "Juba",						"South Sudan" },
	{ "Madrid",						"Spain" },
	{ "Sri Jayawardenepura Kotte",	"Sri Lanka" },
	{ "Khartoum",					"Sudan" },
	{ "Paramaribo",					"Suriname" },
	{ "Stockholm",					"Sweden" },
	{ "Bern",						"Switzerland" },
	{ "Damascus",					"Syria" },
	{ "Taipei",						"Taiwan" },
	{ "Dushanbe",					"Tajikistan" },
	{ "Dodoma",						"Tanzania" },
	{ "Bangkok",					"Thailand" },
	{ "Banjul",						"The Gambia" },
	{ "Lomé",						"Togo" },
	{ "Nukuʻalofa",					"Tonga" },
	{ "Tiraspol",					"Transnistria" },
	{ "Port of Spain", 				"Trinidad and Tobago" },
	{ "Tunis",						"Tunisia" },
	{ "Ankara",						"Turkey" },
	{ "Ashgabat",					"Turkmenistan" },
	{ "Cockburn Town", 				"Turks and Caicos Islands" },
	{ "Funafuti",					"Tuvalu" },
	{ "Kampala",					"Uganda" },
	{ "Kyiv",						"Ukraine" },
	{ "Abu Dhabi",					"United Arab Emirates" },
	{ "London",						"United Kingdom" },
	{ "Washington, D.C.",	 		"United States" },
	{ "Charlotte Amalie",	 		"United States Virgin Islands" },
	{ "Montevideo",					"Uruguay" },
	{ "Tashkent",					"Uzbekistan" },
	{ "Port Vila",					"Vanuatu" },
	{ "Vatican City",	 			"Vatican City" },
	{ "Caracas",					"Venezuela" },
	{ "Hanoi",						"Vietnam" },
	{ "Mata Utu",					"Wallis and Futuna" },
	{ "El Aaiún",					"Western Sahara" },
	{ "Sana'a",						"Yemen" },
	{ "Lusaka",						"Zambia" },
	{ "Harare",						"Zimbabwe" } };


array <array<string>> inventions = {
	{ "~500",	"spinning wheel" },
	{ "577",	"matches" },
	{ "589",	"toilet paper" },
	{ "650",	"windmill" },
	{ "1286",	"eyeglasses" },
	{ "1439",	"printing press" },
	{ "1738",	"mechanized cotton spinning machine" },
	{ "1804",	"steam locomotive" },
	{ "1810",	"wristwatch" },
	{ "1825",	"electromagnet" },
	{ "1855",	"color photography" },
	{ "1879",	"light bulb" },
	{ "1893",	"diesel engine" },
	{ "1935",	"nylon" },
	{ "1941",	"polyester" },
	{ "1956",	"hard disk drive" },
	{ "1957",	"personal computer" },
	{ "1970",	"pocket calculator" },
	{ "1971",	"e-mail" },
	{ "1978",	"GPS" },
	{ "1982",	"CD-ROM" },
	{ "1990",	"World Wide Web" },
	{ "1994",	"Bluetooth" },
	{ "1995",	"DVD" } };























